version: "3"
services:
  bootstrap-node:
    image: kademlia
    volumes:
      - ./bin:/app/
      - ./container_init/bootstrap:/init/
    stdin_open: true
    networks:
      kademlia-network:
        ipv4_address: 10.0.0.2
    ports:
      - 10000:8080

  kademlia-node:
    image: kademlia
    volumes:
      - ./bin:/app/
      - ./container_init/kademlia:/init/
    stdin_open: true
    networks:
      - kademlia-network

networks:
  kademlia-network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/24
