version: "3"
services:
  kademliaNodes:
    image: larjim/kademlialab:latest
    volumes:
      - .:/src/
    working_dir: /src/
    stdin_open: true
    tty: true
    deploy:
      replicas: 50 
#        resources:
#           limits:
#              cpus: "0.1"
#              memory: 50M
      restart_policy:
        condition: on-failure
#    ports:
#      - "6000:6000"
    networks:
      - kademlia_network
      
networks:
        kademlia_network:
